spring:
  application:
    name: login-agg


# 滑块验证码配置， 详细请看 cloud.tianai.captcha.autoconfiguration.ImageCaptchaProperties 类
captcha:
  # 如果项目中使用到了redis，滑块验证码会自动把验证码数据存到redis中， 这里配置redis的key的前缀,默认是captcha:slider
  prefix: echovale:captcha
  # 验证码过期时间，默认是2分钟,单位毫秒， 可以根据自身业务进行调整
  expire:
    # 默认缓存时间 2分钟
    default: 120000
    # 针对 点选验证码 过期时间设置为 2分钟， 因为点选验证码验证比较慢，把过期时间调整大一些
    WORD_IMAGE_CLICK: 20000
  # 使用加载系统自带的资源， 默认是 false(这里系统的默认资源包含 滑动验证码模板/旋转验证码模板,如果想使用系统的模板，这里设置为true)
  init-default-resource: true
  # 缓存控制， 默认为false不开启
  local-cache-enabled: true
  # 缓存开启后，验证码会提前缓存一些生成好的验证数据， 默认是20
  local-cache-size: 20
  # 缓存开启后，缓存拉取失败后等待时间 默认是 5秒钟
  local-cache-wait-time: 5000
  # 缓存开启后，缓存检查间隔 默认是2秒钟
  local-cache-period: 2000
  # 配置字体包，供文字点选验证码使用,可以配置多个，不配置使用默认的字体
  font-path:
    - classpath:font/SimHei.ttf
  secondary:
    # 二次验证， 默认false 不开启
    enabled: true
    # 二次验证过期时间， 默认 2分钟
    expire: 120000
    # 二次验证缓存key前缀，默认是 captcha:secondary
    keyPrefix: "captcha:secondary"

login:
  security:
    jwt:
      secret: "oD4oE1gQ8hI6jA0nG9gC2hJ1gE6dK4jA"
      issuer: "WHITEXUAN@2323"
      access-expiration: 2h
      refresh-expiration: 7d
    image-captcha:
      debug-secondary-token: "rhW1GZAOVlO5F3OhkU2RpOhUrnK1tIEKfPyQmLvZrh9Z9anRQGwcxpo2XMp7DXfRjf9YSywGEaWKxG8REuz7yXIbHIKafa02oBNGGfWt3qRyQFIeohLQIYhN0IawVKwV"
      secondary-token-header-name: "Secondary-Token"

  redis:
    refresh-token-prefix: "refresh_token"
    refresh-token-expire: 2m
    login-record-prefix: "login_record"
    login-record-expire: 5m
    login-locked-prefix: "login_locked"
    login-locked-expire: 2h
    login-id-record-max-times: 5
    login-ip-record-max-times: 30

  strategy:
#    captcha-unauthorized-message:
#    password-unauthorized-message:
    dummy-credential: "dummy-pT1]hF1@cU2>"
    bad-conditions-message: "登录次数过多，请稍后重新尝试"
    password-unauthorized-message: "用户名或密码错误"
    captcha-unauthorized-message: "用户名或验证码错误"

