spring:
  application:
    name: echovale-root-app

  profiles:
    active: music, login
  config:
    import:
      - optional:classpath:/application-login.yml

  output:
    ansi:
      enabled: always

  jackson:
    default-property-inclusion: non_empty

  datasource:
    username: root
    password: 248812
    url: jdbc:mysql://localhost:3306/echovale
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
      password:


server:
  port: 8080
  address: localhost



logging:
  level:
    org.springframework.jdbc: debug
  #    com.baomidou.dynamic: off
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss}){faint} [%thread] %clr(%-5level){highlight} %clr(%36.36logger{36}){cyan}: %msg%n"



mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id

