spring:
  application:
    name: echovale-web-api

  profiles:
    active: datasource, service

  output:
    ansi:
      enabled: always

  jackson:
    default-property-inclusion: non_empty

server:
  port: 8080
  address: 0.0.0.0



logging:
  level:
    org.springframework.jdbc: debug
#    com.baomidou.dynamic: off
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss}){faint} [%thread] %clr(%-5level){highlight} %clr(%36.36logger{36}){cyan}: %msg%n"


